# Generated by Django 4.2.3 on 2023-07-22 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('kiosk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.kiosk')),
            ],
        ),
    ]
