# Generated by Django 4.2.3 on 2023-07-25 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0001_initial'),
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('kiosk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.kiosk')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('kiosk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.kiosk')),
            ],
        ),
        migrations.CreateModel(
            name='ScoredFeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('timeout', models.PositiveSmallIntegerField(default=60)),
                ('kiosk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.kiosk')),
            ],
        ),
        migrations.CreateModel(
            name='ScoredFeedbackOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('text', models.CharField(max_length=256)),
                ('follow_up_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='feedback.form')),
                ('follow_up_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='feedback.question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.scoredfeedbackquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('follow_up_form', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='feedback.form')),
                ('follow_up_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='feedback.question')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.question')),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=128)),
                ('label', models.CharField(max_length=128)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedback.form')),
            ],
        ),
    ]
