# Generated by Django 4.2.3 on 2023-07-29 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_form_question_scoredfeedbackquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='feedback.question'),
        ),
        migrations.AlterField(
            model_name='scoredfeedbackoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='feedback.scoredfeedbackquestion'),
        ),
    ]
