# Generated by Django 4.2.3 on 2023-07-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0005_remove_kiosk_lead_scored_feedback_question'),
        ('feedback', '0006_remove_question_kiosk_remove_formfield_form_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScoredFeedbackOption',
            new_name='ScoredOption',
        ),
        migrations.DeleteModel(
            name='ScoredFeedbackQuestion',
        ),
    ]
