# Generated by Django 4.2.3 on 2023-07-31 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0008_flow_end_block'),
        ('feedback', '0008_rename_kiosk_rating_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoredoption',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scored_options', to='kiosk.block'),
        ),
    ]
