# Generated by Django 4.2.4 on 2023-08-13 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0010_rename_flow_rating_survey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoredoption',
            options={'ordering': ('score',)},
        ),
    ]
