steps:
- id: pull
  name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'europe-west1-docker.pkg.dev/roiiogcloud/kioskbear/kioskbear:latest']
- id: build
  name: 'gcr.io/cloud-builders/docker'
  args: [
    "build",
    '--cache-from',
    'europe-west1-docker.pkg.dev/roiiogcloud/kioskbear/kioskbear:latest',
    "-t", "europe-west1-docker.pkg.dev/roiiogcloud/kioskbear/kioskbear:$REVISION_ID",
    "-t", "europe-west1-docker.pkg.dev/roiiogcloud/kioskbear/kioskbear:latest",
    "."]
- id: deploy-quizportal
  name: 'gcr.io/cloud-builders/kubectl'
  args:
  - set
  - image
  - deployment
  - kioskbear
  - django=europe-west1-docker.pkg.dev/roiiogcloud/kioskbear/kioskbear:$REVISION_ID
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-west1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-2'
images:
- 'europe-west1-docker.pkg.dev/roiiogcloud/kioskbear/kioskbear:$REVISION_ID'
- 'europe-west1-docker.pkg.dev/roiiogcloud/kioskbear/kioskbear:latest'
