# Generated by Django 4.2.3 on 2023-07-29 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_block_kiosk_start_block'),
        ('feedback', '0003_alter_option_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoredfeedbackoption',
            name='question',
        ),
        migrations.AddField(
            model_name='scoredfeedbackoption',
            name='block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kiosk.block'),
            preserve_default=False,
        ),
    ]
