# Generated by Django 4.2.3 on 2023-07-29 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_block_kiosk_start_block'),
        ('feedback', '0004_remove_scoredfeedbackoption_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoredfeedbackoption',
            name='follow_up_form',
        ),
        migrations.RemoveField(
            model_name='scoredfeedbackoption',
            name='follow_up_question',
        ),
        migrations.AddField(
            model_name='scoredfeedbackoption',
            name='follow_up_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='options', to='kiosk.block'),
        ),
    ]
