# Generated by Django 4.2.3 on 2023-07-29 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0004_remove_kiosk_lead_form'),
        ('feedback', '0005_remove_scoredfeedbackoption_follow_up_form_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='kiosk',
        ),
        migrations.RemoveField(
            model_name='formfield',
            name='form',
        ),
        migrations.RemoveField(
            model_name='option',
            name='follow_up_form',
        ),
        migrations.RemoveField(
            model_name='option',
            name='follow_up_question',
        ),
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.AddField(
            model_name='formfield',
            name='block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kiosk.block'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='kiosk.block'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='option',
            name='follow_up_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kiosk.block'),
        ),
        migrations.AlterField(
            model_name='scoredfeedbackoption',
            name='follow_up_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kiosk.block'),
        ),
        migrations.DeleteModel(
            name='Form',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
