# Generated by Django 4.2.3 on 2023-07-30 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_rename_scoredfeedbackoption_scoredoption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='kiosk',
            new_name='flow',
        ),
    ]
