# Generated by Django 4.2.4 on 2023-08-13 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0009_alter_scoredoption_block'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='flow',
            new_name='survey',
        ),
    ]
