# Generated by Django 4.2.3 on 2023-07-29 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0004_remove_kiosk_lead_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kiosk',
            name='lead_scored_feedback_question',
        ),
    ]
