# Generated by Django 4.2.3 on 2023-07-30 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_rename_scoredfeedbackoption_scoredoption_and_more'),
        ('accounts', '0003_alter_account_customer'),
        ('kiosk', '0005_remove_kiosk_lead_scored_feedback_question'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kiosk',
            new_name='Flow',
        ),
    ]
