# Generated by Django 4.2.3 on 2023-07-31 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0007_rename_kiosk_block_flow_alter_flow_start_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='end_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kiosk.block'),
        ),
    ]
