# Generated by Django 4.2.4 on 2023-08-13 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_customer'),
        ('feedback', '0009_alter_scoredoption_block'),
        ('kiosk', '0008_flow_end_block'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flow',
            new_name='Survey',
        ),
    ]
