# Generated by Django 4.2.4 on 2023-08-13 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0009_rename_flow_survey'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='flow',
            new_name='survey',
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveys', to='kiosk.block'),
        ),
    ]
