# Generated by Django 4.2.3 on 2023-07-25 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_form_question_scoredfeedbackquestion_and_more'),
        ('kiosk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiosk',
            name='lead_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kiosks', to='feedback.form'),
        ),
        migrations.AddField(
            model_name='kiosk',
            name='lead_scored_feedback_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='kiosks', to='feedback.scoredfeedbackquestion'),
        ),
    ]
