# Generated by Django 4.2.3 on 2023-07-29 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_kiosk_lead_form_kiosk_lead_scored_feedback_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('kiosk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kiosk.kiosk')),
            ],
        ),
        migrations.AddField(
            model_name='kiosk',
            name='start_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiosks', to='kiosk.block'),
        ),
    ]
