# Generated by Django 4.2.3 on 2023-07-29 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_block_kiosk_start_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kiosk',
            name='lead_form',
        ),
    ]
