# Generated by Django 4.2.3 on 2023-07-30 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0006_rename_kiosk_flow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='kiosk',
            new_name='flow',
        ),
        migrations.AlterField(
            model_name='flow',
            name='start_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flows', to='kiosk.block'),
        ),
    ]
